#PBS -q regular
#PBS -l mppwidth=24
#PBS -l walltime=00:35:00
#PBS -N ff.t
#PBS -e ff.t.$PBS_JOBID.err
#PBS -o ff.t.$PBS_JOBID.out

module load ffmpeg
cd $GSCRATCH/images
rm Tambora+obs.354.mp4
find Tambora+obs.3.5.4/*.png -size -1 -exec rm {} \;
aprun -n 1 -d 24 ffmpeg -r 48 -pattern_type glob -i Tambora+obs.3.5.4/\*.png -c:v libx264 -threads 16 -preset slow -tune animation -profile:v high -level 4.2 -pix_fmt yuv420p -crf 22 -c:a copy Tambora+obs.354.mp4

