#PBS -q regular
#PBS -l mppwidth=24
#PBS -l walltime=00:35:00
#PBS -N ff.t
#PBS -e ff.t.$PBS_JOBID.err
#PBS -o ff.t.$PBS_JOBID.out

module load ffmpeg
cd $GSCRATCH/images
rm Tambora.356.mp4
find Tambora.3.5.6/*.png -size -1 -exec rm {} \;
aprun -n 1 -d 24 ffmpeg -r 48 -pattern_type glob -i Tambora.3.5.6/\*.png -c:v libx264 -threads 16 -preset slow -tune animation -profile:v high -level 4.1 -pix_fmt yuv420p -crf 22 -c:a copy Tambora.356.mp4

